# Generated by Django 4.0.4 on 2022-05-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_director_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='review',
            name='project',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
