# Generated by Django 4.0.4 on 2022-05-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_rename_movie_title_movie_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='movie_name',
        ),
    ]
