# Generated by Django 4.0.4 on 2022-05-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_rename_name_movie_movie_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
